// Command gen-ship-loadout-backfill generates the ships.equipment backfill
// (migration 0057, TASK-100.3.25). Before this task a player ship spawned with
// equipment='[]' and only its bare class stats; the spawn/purchase path now fits
// the class's base module set (ct_npc_ship_modules) and folds its stat effects.
// Ships created before the change sit un-fitted, so their outfit tab is a wall
// of disabled buttons and their stats miss the base-kit boosts.
//
// It reads the ship-class catalog, the base-loadout catalog and the equipment
// catalog — the same sources the spawner uses — and, for every class with a
// non-empty loadout, folds the loadout onto the class base (via the shared
// balance.ApplyEquipmentEffects / EnergyDelta) and emits one UPDATE that writes
// the equipment JSONB plus every stat column the folding touches:
//
//	UPDATE ships SET equipment = '<jsonb>'::jsonb, max_shield = …, shield = …,
//	    max_energy = …, energy = …, energy_delta = …, max_speed = …,
//	    acceleration = …, shield_recharge = …, energy_recharge = …,
//	    laser_damage = …, turn_rate = …, cargobay = …, radar_range = …
//	WHERE ship_class_id = <id> AND equipment = '[]'::jsonb AND is_spacesuit = false
//	  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');
//
// Only still-un-fitted (equipment='[]'), non-spacesuit, non-NPC ships are
// touched, so already-outfitted ships and NPC ships are left alone. The base
// stats reproduce internal/app.baseShipStats with the default spawn config
// (ShipSpawnerConfig{}.withDefaults()), which app.go always uses — rerun this
// tool if those defaults or the catalogs change.
//
// Usage:
//
//	go run ./cmd/starwind-tools/gen-ship-loadout-backfill \
//	    -classes configs/ship_classes.yaml \
//	    -loadouts configs/ship_base_loadout.yaml \
//	    -equipment configs/equipment.yaml \
//	    -out migrations/0057_ship_base_loadout_backfill.sql
package main

import (
	"flag"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"

	"spaceempire/back/internal/balance"
	"spaceempire/back/internal/domain"
)

// Spawn-config defaults mirrored from internal/app.ShipSpawnerConfig.withDefaults()
// + race_fleet_spawner.warshipLaserDivisor. app.go builds spawnCfg from pure
// defaults, so these are the exact values baseShipStats sees at runtime.
const (
	startEnergy         = 100
	startEnergyRecharge = 2
	startLaserDamage    = 10
	warshipLaserDivisor = 10
)

var startTurnRate = math.Pi / 4

// npcLoginSubquery excludes the reserved system player that owns every NPC ship
// (seeded by migration 0024). Empty subquery → NOT IN keeps all rows; the login
// is unique, so the subquery yields at most one non-null id.
const npcLoginSubquery = "(SELECT id FROM players WHERE login = '__npc__')"

func main() {
	classesFile := flag.String("classes", "configs/ship_classes.yaml", "path to the ship-class catalog")
	loadoutsFile := flag.String("loadouts", "configs/ship_base_loadout.yaml", "path to the base-loadout catalog")
	equipFile := flag.String("equipment", "configs/equipment.yaml", "path to the equipment catalog")
	out := flag.String("out", "migrations/0057_ship_base_loadout_backfill.sql", "output migration path")
	flag.Parse()
	if err := run(*classesFile, *loadoutsFile, *equipFile, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(classesFile, loadoutsFile, equipFile, outPath string) error {
	classes, err := balance.LoadShipClassesFromFile(classesFile)
	if err != nil {
		return fmt.Errorf("load ship classes: %w", err)
	}
	loadouts, err := balance.LoadShipLoadoutsFromFile(loadoutsFile)
	if err != nil {
		return fmt.Errorf("load ship loadouts: %w", err)
	}
	equipment, err := balance.LoadEquipmentFromFile(equipFile)
	if err != nil {
		return fmt.Errorf("load equipment: %w", err)
	}

	migration, updates := render(classes, loadouts, equipment)
	if err := os.WriteFile(outPath, []byte(migration), 0o644); err != nil {
		return fmt.Errorf("write migration: %w", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d loadout backfill UPDATE(s) to %s\n", updates, outPath)
	return nil
}

func render(classes *balance.ShipClasses, loadouts *balance.ShipLoadouts, equipment *balance.Equipments) (string, int) {
	var b strings.Builder
	b.WriteString("-- +goose Up\n-- +goose StatementBegin\n")
	b.WriteString("-- Backfill ships.equipment + folded stat columns for existing player ships\n")
	b.WriteString("-- (TASK-100.3.25), generated by cmd/starwind-tools/gen-ship-loadout-backfill.\n")
	b.WriteString("-- Ships created before base-loadout spawning sit at equipment='[]' with only\n")
	b.WriteString("-- their bare class stats. Each UPDATE fits the class's base module set\n")
	b.WriteString("-- (ct_npc_ship_modules) and writes the equipment JSONB plus every stat the fold\n")
	b.WriteString("-- touches. Only un-fitted, non-spacesuit, non-NPC ships are touched; shield and\n")
	b.WriteString("-- energy are topped up to their new maxima. Do not edit by hand — rerun the\n")
	b.WriteString("-- generator.\n\n")

	updates := 0
	for _, cls := range classes.AllShipClasses() {
		lo := loadouts.BaseLoadout(cls.Race, cls.Type)
		if len(lo) == 0 {
			continue
		}
		base := baseStats(cls)
		eff := balance.ApplyEquipmentEffects(base, lo)
		energyDelta := equipment.EnergyDelta(lo)
		jsonb := equipmentJSON(lo)

		fmt.Fprintf(&b, "UPDATE ships SET\n")
		fmt.Fprintf(&b, "    equipment       = '%s'::jsonb,\n", jsonb)
		fmt.Fprintf(&b, "    max_speed       = %s,\n", ftoa(eff.MaxSpeed))
		fmt.Fprintf(&b, "    acceleration    = %s,\n", ftoa(eff.Acceleration))
		fmt.Fprintf(&b, "    turn_rate       = %s,\n", ftoa(eff.TurnRate))
		fmt.Fprintf(&b, "    max_shield      = %d,\n", eff.MaxShield)
		fmt.Fprintf(&b, "    shield          = %d,\n", eff.MaxShield)
		fmt.Fprintf(&b, "    shield_recharge = %d,\n", eff.ShieldRecharge)
		fmt.Fprintf(&b, "    max_energy      = %d,\n", eff.MaxEnergy)
		fmt.Fprintf(&b, "    energy          = %d,\n", eff.MaxEnergy)
		fmt.Fprintf(&b, "    energy_recharge = %d,\n", eff.EnergyRecharge)
		fmt.Fprintf(&b, "    energy_delta    = %d,\n", energyDelta)
		fmt.Fprintf(&b, "    laser_damage    = %d,\n", eff.LaserDamage)
		fmt.Fprintf(&b, "    radar_range     = %s,\n", ftoa(eff.RadarRange))
		fmt.Fprintf(&b, "    cargobay        = %s\n", ftoa(eff.CargoBay))
		fmt.Fprintf(&b, "WHERE ship_class_id = %d AND equipment = '[]'::jsonb AND is_spacesuit = false\n", int(cls.ID))
		fmt.Fprintf(&b, "  AND player_id NOT IN %s;\n\n", npcLoginSubquery)
		updates++
	}

	b.WriteString("-- +goose StatementEnd\n\n")
	b.WriteString("-- +goose Down\n-- +goose StatementBegin\n")
	b.WriteString("-- Undo: strip the backfilled equipment back to '[]'. The stat columns are\n")
	b.WriteString("-- left as-is (a no-op reverse would need every ship's pre-backfill values,\n")
	b.WriteString("-- which are not recorded); a re-run of Up recomputes them from the class base.\n")
	b.WriteString("UPDATE ships SET equipment = '[]'::jsonb\n")
	b.WriteString("WHERE is_spacesuit = false AND player_id NOT IN " + npcLoginSubquery + ";\n")
	b.WriteString("-- +goose StatementEnd\n")
	return b.String(), updates
}

// baseStats reproduces internal/app.baseShipStats with the default spawn config:
// class supplies speed/accel/shield/laser/radar/cargo; energy pool + turn rate
// come from the spawn-config defaults.
func baseStats(cls balance.ShipClass) balance.ShipStats {
	laser := cls.Laser / warshipLaserDivisor
	if laser < startLaserDamage {
		laser = startLaserDamage
	}
	return balance.ShipStats{
		MaxSpeed:       cls.Speed,
		Acceleration:   cls.Acceleration,
		TurnRate:       startTurnRate,
		MaxShield:      cls.Shield,
		ShieldRecharge: cls.ShieldCharge,
		MaxEnergy:      startEnergy,
		EnergyRecharge: startEnergyRecharge,
		LaserDamage:    laser,
		RadarRange:     float64(cls.Radar),
		CargoBay:       float64(cls.CargoBay),
	}
}

// equipmentJSON renders the loadout the way persistence/ships.equipmentToJSON
// does: a JSON array of {equipmentID, type, level} in loadout order. No single
// quotes appear in the module fields, so it is safe to embed in a SQL literal.
func equipmentJSON(lo []domain.InstalledEquipment) string {
	var b strings.Builder
	b.WriteByte('[')
	for i, m := range lo {
		if i > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(&b, `{"equipmentID":%d,"type":%q,"level":%d}`, int64(m.EquipmentID), m.Type, m.Level)
	}
	b.WriteByte(']')
	return b.String()
}

// ftoa formats a float the shortest way that round-trips, matching how pgx sends
// a Go float64 to a double precision column.
func ftoa(v float64) string {
	return strconv.FormatFloat(v, 'g', -1, 64)
}
