// Command convert-map reads the StarWind galaxy (sectors + gates) from
// sql/db.sql and generates a goose seed migration that replaces the stub
// 10-sector world with the 70 named sectors and their gate topology. One-shot
// tool — rerun whenever the upstream dump changes.
//
// Coordinate transform: StarWind in-sector gate exits sit at ±1280; we scale to
// ±900 (the spaceempire convention, inside the ±1000 sector bounds). Galactic
// grid coords and the 885-station placement are out of MVP scope (see the task
// notes) — this migration ports sectors + gates only.
//
// Usage:
//
//	go run ./cmd/starwind-tools/convert-map \
//	    -sql /path/to/starwind/sql/db.sql \
//	    -out migrations/0034_starwind_map.sql
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	starwindGateExtent = 1280.0 // StarWind gate-exit magnitude
	localGateExtent    = 900.0  // spaceempire gate-exit magnitude (inside ±1000)
	sectorBound        = 1000.0 // local sector half-extent (matches the stub)
)

type sector struct {
	id     int
	name   string
	gx, gy int // galactic grid coordinates (StarWind sectors.pos_x/pos_y)
}

type gate struct {
	s1, s2 int
	x1, y1 float64
	x2, y2 float64
}

func main() {
	sqlFile := flag.String("sql", "", "path to starwind/sql/db.sql")
	out := flag.String("out", "migrations/0034_starwind_map.sql", "output sectors+gates migration path")
	stationsOut := flag.String("stations-out", "migrations/0036_starwind_stations.sql", "output stations migration path")
	gridOut := flag.String("grid-out", "migrations/0039_sector_grid.sql", "output sector grid-coords migration path")
	flag.Parse()
	if *sqlFile == "" {
		fmt.Fprintln(os.Stderr, "-sql is required")
		os.Exit(2)
	}
	if err := run(*sqlFile, *out, *stationsOut, *gridOut); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(sqlFile, outPath, stationsOutPath, gridOutPath string) error {
	abs, err := filepath.Abs(sqlFile)
	if err != nil {
		return fmt.Errorf("resolve sql: %w", err)
	}
	raw, err := os.ReadFile(abs)
	if err != nil {
		return fmt.Errorf("read sql: %w", err)
	}

	sectors, valid, err := parseSectors(raw)
	if err != nil {
		return err
	}
	gates, skipped, err := parseGates(raw, valid)
	if err != nil {
		return err
	}

	body := renderMigration(sectors, gates)
	if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write migration: %w", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d sectors and %d gates to %s (%d gates skipped — endpoint sector missing)\n",
		len(sectors), len(gates), outPath, skipped)

	stations, shipyards, trades, err := parseStatics(raw, valid)
	if err != nil {
		return err
	}
	sbody := renderStationsMigration(stations, shipyards, trades)
	if err := os.WriteFile(stationsOutPath, []byte(sbody), 0o644); err != nil {
		return fmt.Errorf("write stations migration: %w", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d stations, %d shipyards, %d trade_stations to %s\n",
		len(stations), len(shipyards), len(trades), stationsOutPath)

	gbody := renderGridMigration(sectors)
	if err := os.WriteFile(gridOutPath, []byte(gbody), 0o644); err != nil {
		return fmt.Errorf("write grid migration: %w", err)
	}
	fmt.Fprintf(os.Stderr, "wrote grid coords for %d sectors to %s\n", len(sectors), gridOutPath)
	return nil
}

// gridOverrides repositions a few sectors whose StarWind pos_x/pos_y sit far
// from their actual gate neighbours (link_* were 0, so the original schematic
// drew them isolated). On our map every gate is a connector, so those far
// cells produced long diagonal lines. The fixed cells sit next to the
// neighbours they gate to, keeping the connectors short and orthogonal.
var gridOverrides = map[int][2]int{
	25: {50, 55}, // Сектор Х25 (StarWind 1,55): vertical to 50-50, horizontal to 02-55
	33: {48, 55}, // Сектор 02-55 (StarWind 2,55): horizontal to 47-55 and Х25
}

// renderGridMigration emits the galactic grid coordinates (pos_x/pos_y) for the
// ported sectors. They drive the schematic galaxy map (sectors placed on a
// 1..N grid, gates drawn between cells) — see GalaxyMap.tsx. Kept as a separate
// late migration (the sectors table is seeded grid-less in 0034); a single
// UPDATE ... FROM (VALUES ...) backfills every row.
func renderGridMigration(sectors []sector) string {
	var b strings.Builder
	b.WriteString("-- +goose Up\n-- +goose StatementBegin\n")
	b.WriteString("-- Galactic grid coordinates for the ported sectors, generated by\n")
	b.WriteString("-- cmd/starwind-tools/convert-map (StarWind sectors.pos_x/pos_y). Drives the\n")
	b.WriteString("-- schematic galaxy map. Do not edit by hand — rerun the converter.\n")
	b.WriteString("ALTER TABLE sectors\n")
	b.WriteString("    ADD COLUMN IF NOT EXISTS grid_x integer NOT NULL DEFAULT 0,\n")
	b.WriteString("    ADD COLUMN IF NOT EXISTS grid_y integer NOT NULL DEFAULT 0;\n\n")
	b.WriteString("UPDATE sectors AS s SET grid_x = v.gx, grid_y = v.gy\n")
	b.WriteString("FROM (VALUES\n")
	for i, s := range sectors {
		end := ","
		if i == len(sectors)-1 {
			end = ""
		}
		gx, gy := s.gx, s.gy
		if o, ok := gridOverrides[s.id]; ok {
			gx, gy = o[0], o[1]
		}
		fmt.Fprintf(&b, "    (%d, %d, %d)%s\n", s.id, gx, gy, end)
	}
	b.WriteString(") AS v(id, gx, gy)\nWHERE s.id = v.id;\n")
	b.WriteString("-- +goose StatementEnd\n\n")
	b.WriteString("-- +goose Down\n-- +goose StatementBegin\n")
	b.WriteString("ALTER TABLE sectors DROP COLUMN IF EXISTS grid_x;\n")
	b.WriteString("ALTER TABLE sectors DROP COLUMN IF EXISTS grid_y;\n")
	b.WriteString("-- +goose StatementEnd\n")
	return b.String()
}

func parseSectors(raw []byte) ([]sector, map[int]bool, error) {
	tuples, err := tuples(raw, "sectors")
	if err != nil {
		return nil, nil, err
	}
	out := make([]sector, 0, len(tuples))
	valid := make(map[int]bool, len(tuples))
	for _, t := range tuples {
		f := splitFields(t)
		// id, name, pos_x, pos_y, link_left, link_right, link_up, link_down
		if len(f) < 4 {
			return nil, nil, fmt.Errorf("sectors tuple %q: too few fields", t)
		}
		id, err := strconv.Atoi(f[0])
		if err != nil {
			return nil, nil, fmt.Errorf("sector id %q: %w", f[0], err)
		}
		gx, err := strconv.Atoi(f[2])
		if err != nil {
			return nil, nil, fmt.Errorf("sector %d pos_x %q: %w", id, f[2], err)
		}
		gy, err := strconv.Atoi(f[3])
		if err != nil {
			return nil, nil, fmt.Errorf("sector %d pos_y %q: %w", id, f[3], err)
		}
		out = append(out, sector{id: id, name: strings.TrimSpace(f[1]), gx: gx, gy: gy})
		valid[id] = true
	}
	sort.Slice(out, func(i, j int) bool { return out[i].id < out[j].id })
	return out, valid, nil
}

func parseGates(raw []byte, valid map[int]bool) ([]gate, int, error) {
	tuples, err := tuples(raw, "gates")
	if err != nil {
		return nil, 0, err
	}
	var out []gate
	skipped := 0
	for _, t := range tuples {
		f := splitFields(t)
		if len(f) != 11 {
			return nil, 0, fmt.Errorf("gates tuple %q: expected 11 fields, got %d", t, len(f))
		}
		nums := make([]int, 11)
		for i := 0; i < 11; i++ {
			v, err := strconv.Atoi(f[i])
			if err != nil {
				return nil, 0, fmt.Errorf("gate %q field %d: %w", t, i, err)
			}
			nums[i] = v
		}
		if nums[10] == 0 { // builded = 0 → not a real gate
			continue
		}
		s1, s2 := nums[2], nums[5]
		if !valid[s1] || !valid[s2] || s1 == s2 {
			skipped++
			continue
		}
		out = append(out, gate{
			s1: s1, y1: scale(nums[4]), x1: scale(nums[3]),
			s2: s2, x2: scale(nums[6]), y2: scale(nums[7]),
		})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].s1 != out[j].s1 {
			return out[i].s1 < out[j].s1
		}
		return out[i].s2 < out[j].s2
	})
	return out, skipped, nil
}

// scale maps a StarWind in-sector coordinate to the local space, clamped to the
// sector bounds.
func scale(v int) float64 {
	f := float64(v) * localGateExtent / starwindGateExtent
	if f > sectorBound {
		f = sectorBound
	}
	if f < -sectorBound {
		f = -sectorBound
	}
	// round to whole units — coordinates are doubles but the dump is integral.
	return float64(int64(f + sign(f)*0.5))
}

func sign(f float64) float64 {
	if f < 0 {
		return -1
	}
	return 1
}

// --- station placement (phase 9.2) ----------------------------------------

// placed is one imported static: a station, shipyard or trade_station. owner is
// dropped (everything becomes NPC-owned); typ < 0 marks a shipyard (no type).
type placed struct {
	id     int
	typ    int
	sector int
	x, y   float64
	race   int
	built  bool
}

// capitalRace maps each main race's capital sector to its race id
// (race.CentralSector, internal/reference/race). Drives the starter market.
var capitalRace = map[int]int{1: 1, 5: 2, 9: 3, 13: 4, 17: 5}

// layout records the field index of each column we read from a static table;
// typ < 0 means the table has no type column (shipyards).
type layout struct {
	min     int
	id      int
	typ     int
	sector  int
	posX    int
	posY    int
	race    int
	builded int
}

var (
	// ID,owner,type,shield,hull,sector,pos_x,pos_y,race,in_progress,next_cycle_time,builded,...
	stationLayout = layout{min: 12, id: 0, typ: 2, sector: 5, posX: 6, posY: 7, race: 8, builded: 11}
	// ID,owner,race,sector,pos_x,pos_y,shield,hull,builded
	shipyardLayout = layout{min: 9, id: 0, typ: -1, sector: 3, posX: 4, posY: 5, race: 2, builded: 8}
	// ID,owner,type,shield,hull,sector,pos_x,pos_y,race,builded,...
	tradeStationLayout = layout{min: 10, id: 0, typ: 2, sector: 5, posX: 6, posY: 7, race: 8, builded: 9}
)

// parseStatics parses stations/shipyards/trade_stations from the dump, keeping
// only rows whose sector exists in the ported galaxy. Positions are scaled like
// gate exits (±1280→±900, clamped to the sector bounds).
func parseStatics(raw []byte, valid map[int]bool) (stations, shipyards, trades []placed, err error) {
	if stations, err = parsePlaced(raw, "stations", valid, stationLayout); err != nil {
		return nil, nil, nil, err
	}
	if shipyards, err = parsePlaced(raw, "shipyards", valid, shipyardLayout); err != nil {
		return nil, nil, nil, err
	}
	if trades, err = parsePlaced(raw, "trade_stations", valid, tradeStationLayout); err != nil {
		return nil, nil, nil, err
	}
	return stations, shipyards, trades, nil
}

func parsePlaced(raw []byte, table string, valid map[int]bool, l layout) ([]placed, error) {
	rows, err := tuples(raw, table)
	if err != nil {
		return nil, err
	}
	out := make([]placed, 0, len(rows))
	for _, t := range rows {
		f := splitFields(t)
		if len(f) < l.min {
			return nil, fmt.Errorf("%s tuple %q: expected >=%d fields, got %d", table, t, l.min, len(f))
		}
		geti := func(idx int) (int, error) {
			v, e := strconv.Atoi(f[idx])
			if e != nil {
				return 0, fmt.Errorf("%s tuple %q field %d (%q): %w", table, t, idx, f[idx], e)
			}
			return v, nil
		}
		sec, err := geti(l.sector)
		if err != nil {
			return nil, err
		}
		if !valid[sec] {
			continue
		}
		id, err := geti(l.id)
		if err != nil {
			return nil, err
		}
		px, err := geti(l.posX)
		if err != nil {
			return nil, err
		}
		py, err := geti(l.posY)
		if err != nil {
			return nil, err
		}
		race, err := geti(l.race)
		if err != nil {
			return nil, err
		}
		builded, err := geti(l.builded)
		if err != nil {
			return nil, err
		}
		p := placed{id: id, typ: -1, sector: sec, x: scale(px), y: scale(py), race: race, built: builded == 1}
		if l.typ >= 0 {
			if p.typ, err = geti(l.typ); err != nil {
				return nil, err
			}
		}
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].id < out[j].id })
	return out, nil
}

const (
	goodsBatteries = 1
	goodsIron      = 2
	goodsFuel      = 40
)

func renderStationsMigration(stations, shipyards, trades []placed) string {
	var b strings.Builder
	b.WriteString("-- +goose Up\n-- +goose StatementBegin\n")
	b.WriteString("-- StarWind station placement (phase 9.2), generated by\n")
	b.WriteString("-- cmd/starwind-tools/convert-map. Replaces the stub station seed (0004)\n")
	b.WriteString("-- and its market (0007, owner_kind 2/4) with the full dump: 885 stations\n")
	b.WriteString("-- / 10 shipyards / 48 trade_stations, all NPC-owned (owner_id NULL).\n")
	b.WriteString("-- Pirbase market (owner_kind 5) and slaves (0027) are kept. Do not edit\n")
	b.WriteString("-- by hand — rerun the converter.\n\n")

	b.WriteString("DELETE FROM station_goods WHERE owner_kind IN (2, 4);\n")
	b.WriteString("DELETE FROM trade_stations;\n")
	b.WriteString("DELETE FROM shipyards;\n")
	b.WriteString("DELETE FROM stations;\n\n")

	b.WriteString("INSERT INTO stations (id, type, sector_id, pos_x, pos_y, race, built) VALUES\n")
	writeRows(&b, stations, true)
	b.WriteString("INSERT INTO shipyards (id, sector_id, pos_x, pos_y, race, built) VALUES\n")
	writeRows(&b, shipyards, false)
	b.WriteString("INSERT INTO trade_stations (id, type, sector_id, pos_x, pos_y, race, built) VALUES\n")
	writeRows(&b, trades, true)

	b.WriteString("-- Keep the BIGSERIAL sequences past the imported ids.\n")
	b.WriteString("SELECT setval('stations_id_seq',       (SELECT MAX(id) FROM stations));\n")
	b.WriteString("SELECT setval('shipyards_id_seq',      (SELECT MAX(id) FROM shipyards));\n")
	b.WriteString("SELECT setval('trade_stations_id_seq', (SELECT MAX(id) FROM trade_stations));\n\n")

	writeCapitalMarket(&b, stations, trades)

	b.WriteString("-- +goose StatementEnd\n\n")
	b.WriteString("-- +goose Down\n-- +goose StatementBegin\n")
	b.WriteString("-- Irreversible pre-release reseed: drop all stations and their market\n")
	b.WriteString("-- (the stub seed is not restored).\n")
	b.WriteString("DELETE FROM station_goods WHERE owner_kind IN (2, 4);\n")
	b.WriteString("DELETE FROM trade_stations;\n")
	b.WriteString("DELETE FROM shipyards;\n")
	b.WriteString("DELETE FROM stations;\n")
	b.WriteString("-- +goose StatementEnd\n")
	return b.String()
}

func writeRows(b *strings.Builder, rows []placed, withType bool) {
	for i, p := range rows {
		end := ","
		if i == len(rows)-1 {
			end = ";"
		}
		built := "true"
		if !p.built {
			built = "false"
		}
		if withType {
			fmt.Fprintf(b, "    (%d, %d, %d, %.0f, %.0f, %d, %s)%s\n",
				p.id, p.typ, p.sector, p.x, p.y, p.race, built, end)
		} else {
			fmt.Fprintf(b, "    (%d, %d, %.0f, %.0f, %d, %s)%s\n",
				p.id, p.sector, p.x, p.y, p.race, built, end)
		}
	}
	b.WriteString("\n")
}

// writeCapitalMarket seeds a starter market for every main race's capital: the
// capital power plant sells Batteries, and the capital trade station buys
// Batteries and sells Iron + Space Fuel. Only goods seeded in goods_types
// (1/2/40) are used so the station_goods FK holds; prices mirror 0007's scale.
func writeCapitalMarket(b *strings.Builder, stations, trades []placed) {
	secs := make([]int, 0, len(capitalRace))
	for s := range capitalRace {
		secs = append(secs, s)
	}
	sort.Ints(secs)

	var rows []string
	for _, sec := range secs {
		race := capitalRace[sec]
		if pp, ok := firstPowerPlant(stations, sec, race); ok {
			rows = append(rows, fmt.Sprintf("    (2, %d, %d, NULL, 50, 250, 600)", pp, goodsBatteries))
		}
		if ts, ok := firstInSector(trades, sec); ok {
			rows = append(rows,
				fmt.Sprintf("    (4, %d, %d, 35, NULL, 0, 600)", ts, goodsBatteries),
				fmt.Sprintf("    (4, %d, %d, NULL, 65, 200, 800)", ts, goodsIron),
				fmt.Sprintf("    (4, %d, %d, NULL, 75, 300, 800)", ts, goodsFuel))
		}
	}
	if len(rows) == 0 {
		return
	}
	b.WriteString("-- Capital markets: each race capital's power plant sells Batteries;\n")
	b.WriteString("-- its trade station buys Batteries and sells Iron + Space Fuel.\n")
	b.WriteString("INSERT INTO station_goods (owner_kind, owner_id, goods_type_id, buy_price, sell_price, stock, max_stock) VALUES\n")
	b.WriteString(strings.Join(rows, ",\n"))
	b.WriteString(";\n\n")
}

// firstPowerPlant returns the lowest-id power plant in the sector for the race.
// Power plants are type 1 (generic) or race*100+1 (racial variant).
func firstPowerPlant(stations []placed, sector, race int) (int, bool) {
	racial := race*100 + 1
	for _, p := range stations { // id-sorted
		if p.sector == sector && (p.typ == 1 || p.typ == racial) {
			return p.id, true
		}
	}
	return 0, false
}

func firstInSector(rows []placed, sector int) (int, bool) {
	for _, p := range rows { // id-sorted
		if p.sector == sector {
			return p.id, true
		}
	}
	return 0, false
}

func renderMigration(sectors []sector, gates []gate) string {
	var b strings.Builder
	b.WriteString("-- +goose Up\n-- +goose StatementBegin\n")
	b.WriteString("-- StarWind 70-sector galaxy (phase 8.19), generated by\n")
	b.WriteString("-- cmd/starwind-tools/convert-map. Replaces the 10-sector stub topology\n")
	b.WriteString("-- (sectors upserted by id; gates fully replaced). Stations/grid coords\n")
	b.WriteString("-- are out of MVP scope — do not edit by hand, rerun the converter.\n\n")

	b.WriteString("INSERT INTO sectors (id, name, min_x, min_y, max_x, max_y) VALUES\n")
	for i, s := range sectors {
		comma := ","
		if i == len(sectors)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "    (%d, %s, %.0f, %.0f, %.0f, %.0f)%s\n",
			s.id, sqlString(s.name), -sectorBound, -sectorBound, sectorBound, sectorBound, comma)
	}
	b.WriteString("ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name,\n")
	b.WriteString("    min_x = EXCLUDED.min_x, min_y = EXCLUDED.min_y,\n")
	b.WriteString("    max_x = EXCLUDED.max_x, max_y = EXCLUDED.max_y;\n\n")

	b.WriteString("DELETE FROM gates;\n")
	b.WriteString("INSERT INTO gates (sector_a, pos_a_x, pos_a_y, sector_b, pos_b_x, pos_b_y) VALUES\n")
	for i, g := range gates {
		comma := ","
		if i == len(gates)-1 {
			comma = ";"
		}
		fmt.Fprintf(&b, "    (%d, %.0f, %.0f, %d, %.0f, %.0f)%s\n",
			g.s1, g.x1, g.y1, g.s2, g.x2, g.y2, comma)
	}

	b.WriteString("-- +goose StatementEnd\n\n")
	b.WriteString("-- +goose Down\n-- +goose StatementBegin\n")
	b.WriteString("-- Irreversible pre-release reseed: just drop the gates (the stub\n")
	b.WriteString("-- topology is not restored). Sectors keep their StarWind names.\n")
	b.WriteString("DELETE FROM gates;\n")
	b.WriteString("-- +goose StatementEnd\n")
	return b.String()
}

// sqlString single-quotes a string for SQL, doubling embedded quotes.
func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// --- shared dump-parsing helpers (same as the other converters) ------------

func tuples(raw []byte, table string) ([]string, error) {
	v, err := sliceInsertValues(raw, table)
	if err != nil {
		return nil, err
	}
	return splitTopLevelTuples(strings.TrimSpace(string(v)))
}

func sliceInsertValues(dump []byte, table string) ([]byte, error) {
	marker := []byte("INSERT INTO `" + table + "` VALUES ")
	idx := bytes.Index(dump, marker)
	if idx < 0 {
		return nil, fmt.Errorf("marker %q not found", marker)
	}
	rest := dump[idx+len(marker):]
	end := bytes.IndexByte(rest, ';')
	if end < 0 {
		return nil, fmt.Errorf("no statement terminator after %q", marker)
	}
	return rest[:end], nil
}

func splitTopLevelTuples(s string) ([]string, error) {
	var out []string
	var buf bytes.Buffer
	depth, inStr := 0, false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inStr:
			if c == '\'' {
				if i+1 < len(s) && s[i+1] == '\'' {
					buf.WriteByte(c)
					buf.WriteByte(s[i+1])
					i++
					continue
				}
				inStr = false
			}
			buf.WriteByte(c)
		case c == '\'':
			inStr = true
			buf.WriteByte(c)
		case c == '(':
			depth++
			if depth == 1 {
				buf.Reset()
				continue
			}
			buf.WriteByte(c)
		case c == ')':
			depth--
			if depth == 0 {
				out = append(out, buf.String())
				continue
			}
			buf.WriteByte(c)
		default:
			buf.WriteByte(c)
		}
	}
	if depth != 0 || inStr {
		return nil, fmt.Errorf("unbalanced tuple list")
	}
	return out, nil
}

func splitFields(s string) []string {
	var out []string
	var buf bytes.Buffer
	inStr := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inStr:
			if c == '\'' {
				if i+1 < len(s) && s[i+1] == '\'' {
					buf.WriteByte('\'')
					i++
					continue
				}
				inStr = false
				continue
			}
			buf.WriteByte(c)
		case c == '\'':
			inStr = true
		case c == ',':
			out = append(out, strings.TrimSpace(buf.String()))
			buf.Reset()
		default:
			buf.WriteByte(c)
		}
	}
	out = append(out, strings.TrimSpace(buf.String()))
	return out
}
