-- +goose Up
-- +goose StatementBegin
-- Galactic grid coordinates for the ported sectors, generated by
-- cmd/starwind-tools/convert-map (StarWind sectors.pos_x/pos_y). Drives the
-- schematic galaxy map. Do not edit by hand — rerun the converter.
ALTER TABLE sectors
    ADD COLUMN IF NOT EXISTS grid_x integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS grid_y integer NOT NULL DEFAULT 0;

UPDATE sectors AS s SET grid_x = v.gx, grid_y = v.gy
FROM (VALUES
    (1, 45, 48),
    (2, 45, 49),
    (3, 46, 48),
    (4, 45, 47),
    (5, 50, 43),
    (6, 49, 43),
    (7, 51, 43),
    (8, 51, 44),
    (9, 45, 56),
    (10, 46, 56),
    (11, 44, 56),
    (12, 44, 57),
    (13, 54, 48),
    (14, 54, 49),
    (15, 54, 47),
    (16, 55, 47),
    (17, 54, 57),
    (18, 54, 56),
    (19, 54, 58),
    (20, 55, 58),
    (21, 59, 53),
    (22, 59, 54),
    (23, 58, 53),
    (24, 59, 52),
    (25, 50, 55),
    (26, 1, 45),
    (27, 47, 1),
    (28, 53, 1),
    (29, 99, 45),
    (30, 99, 55),
    (31, 53, 99),
    (32, 47, 99),
    (33, 48, 55),
    (34, 2, 45),
    (35, 47, 2),
    (36, 53, 2),
    (37, 98, 45),
    (38, 98, 55),
    (39, 53, 98),
    (40, 47, 98),
    (41, 50, 50),
    (42, 50, 49),
    (43, 50, 48),
    (44, 50, 47),
    (45, 49, 47),
    (46, 49, 48),
    (47, 49, 49),
    (48, 50, 53),
    (49, 51, 52),
    (50, 51, 49),
    (51, 51, 48),
    (52, 51, 46),
    (53, 49, 46),
    (54, 48, 48),
    (55, 48, 49),
    (56, 48, 52),
    (57, 48, 54),
    (58, 49, 54),
    (59, 51, 54),
    (60, 52, 54),
    (61, 52, 52),
    (62, 52, 51),
    (63, 52, 49),
    (64, 52, 47),
    (65, 47, 45),
    (66, 47, 50),
    (67, 47, 55),
    (68, 53, 55),
    (69, 53, 50),
    (70, 53, 45)
) AS v(id, gx, gy)
WHERE s.id = v.id;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE sectors DROP COLUMN IF EXISTS grid_x;
ALTER TABLE sectors DROP COLUMN IF EXISTS grid_y;
-- +goose StatementEnd
