-- +goose Up
-- +goose StatementBegin
-- Universal trade-station / pirbase market (phase 10.19 follow-up),
-- generated by cmd/starwind-tools/gen-trade-markets. Every built trade
-- station (owner_kind 4) and pirbase (owner_kind 5) trades every commodity
-- good: it buys any good from the player (buy_price) and sells any good it
-- has in stock (sell_price). Prices are FLAT — parity with the original
-- StarWind Trade SP (the dynamic avg<->max pricing of phase 10.18 stays
-- exclusive to production factories). Replaces the narrow 0036/0043 trade-
-- station seed and the 0027/0004 pirbase seed. Do not edit — rerun the tool.

DELETE FROM station_goods WHERE owner_kind IN (4, 5);

INSERT INTO station_goods (owner_kind, owner_id, goods_type_id, buy_price, sell_price, stock, max_stock)
SELECT o.owner_kind, o.owner_id, g.gid, g.buy_price, g.sell_price, 500, 1000000
FROM (
    SELECT 4 AS owner_kind, id AS owner_id FROM trade_stations WHERE built
    UNION ALL
    SELECT 5 AS owner_kind, id AS owner_id FROM pirbases WHERE built
) o
CROSS JOIN (VALUES
    (1, 8, 10),
    (2, 62, 75),
    (3, 252, 303),
    (4, 840, 1008),
    (5, 1485, 1634),
    (6, 112, 135),
    (7, 6740, 8088),
    (8, 20, 24),
    (9, 81, 98),
    (10, 370, 407),
    (11, 1106, 1217),
    (12, 2222, 2445),
    (13, 5561, 6118),
    (14, 11110, 12221),
    (20, 106766, 117443),
    (21, 3883, 4272),
    (22, 11440, 12584),
    (23, 88723, 97596),
    (24, 1100000, 1210000),
    (25, 948, 1043),
    (26, 31484, 34633),
    (27, 1247638, 1372402),
    (28, 1423044, 1707653),
    (40, 360, 432),
    (60, 52, 63),
    (61, 42, 51),
    (62, 55, 66),
    (63, 105, 126),
    (64, 15, 18),
    (65, 84, 101),
    (66, 52, 63),
    (67, 210, 252),
    (68, 16, 20),
    (69, 42, 51),
    (70, 42, 51),
    (101, 5000000, 6000000),
    (102, 1, 2),
    (103, 8, 10),
    (104, 1, 2),
    (105, 1, 2),
    (112, 431, 518),
    (113, 31, 38),
    (114, 31, 38),
    (301, 506, 608),
    (302, 809, 971),
    (303, 3413, 4096),
    (304, 8550, 10260),
    (305, 20313, 24376),
    (306, 90625, 108750),
    (307, 145115, 174138),
    (308, 393830, 472596),
    (309, 547940, 657528),
    (310, 113314, 135977),
    (311, 231561, 277874),
    (312, 540230, 648276),
    (313, 231561, 277874),
    (314, 540230, 648276),
    (315, 45316, 54380),
    (316, 5479426, 6575312),
    (317, 10000, 12000),
    (318, 250000, 300000),
    (319, 5479426, 6575312),
    (320, 2900232, 3480279),
    (321, 979027, 1174833),
    (322, 9479027, 11374833)
) AS g(gid, buy_price, sell_price);

-- Pirbases also trade slaves (323): buy from the player, sell back at a
-- markup. Start with none in stock — buyable only once some are sold here.
INSERT INTO station_goods (owner_kind, owner_id, goods_type_id, buy_price, sell_price, stock, max_stock)
SELECT 5, pb.id, 323, 800, 1000, 0, 1000000000
FROM pirbases pb WHERE pb.built;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Irreversible pre-release reseed: drops every trade-station / pirbase
-- market (the narrow 0036/0043/0027 seeds are not restored).
DELETE FROM station_goods WHERE owner_kind IN (4, 5);
-- +goose StatementEnd
