-- +goose Up
-- +goose StatementBegin
-- Backfill ships.equipment + folded stat columns for existing player ships
-- (TASK-100.3.25), generated by cmd/starwind-tools/gen-ship-loadout-backfill.
-- Ships created before base-loadout spawning sit at equipment='[]' with only
-- their bare class stats. Each UPDATE fits the class's base module set
-- (ct_npc_ship_modules) and writes the equipment JSONB plus every stat the fold
-- touches. Only un-fitted, non-spacesuit, non-NPC ships are touched; shield and
-- energy are topped up to their new maxima. Do not edit by hand — rerun the
-- generator.

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 11.34,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1138500,
    shield          = 1138500,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1743,
    radar_range     = 450,
    cargobay        = 68260
WHERE ship_class_id = 73 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 17.82,
    acceleration    = 6.237,
    turn_rate       = 0.7853981633974483,
    max_shield      = 633600,
    shield          = 633600,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 3630,
    radar_range     = 450,
    cargobay        = 3300
WHERE ship_class_id = 74 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 32.184,
    acceleration    = 22.5288,
    turn_rate       = 0.7853981633974483,
    max_shield      = 66000,
    shield          = 66000,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 386,
    radar_range     = 450,
    cargobay        = 176
WHERE ship_class_id = 75 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 52.056000000000004,
    acceleration    = 41.644800000000004,
    turn_rate       = 0.7853981633974483,
    max_shield      = 27776,
    shield          = 27776,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 229,
    radar_range     = 450,
    cargobay        = 114
WHERE ship_class_id = 76 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 65.44800000000001,
    acceleration    = 58.9032,
    turn_rate       = 0.7853981633974483,
    max_shield      = 10695,
    shield          = 10695,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 146,
    radar_range     = 500,
    cargobay        = 50
WHERE ship_class_id = 77 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 25.704,
    acceleration    = 8.9964,
    turn_rate       = 0.7853981633974483,
    max_shield      = 265650,
    shield          = 265650,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1240,
    radar_range     = 420,
    cargobay        = 1000
WHERE ship_class_id = 78 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 19.116,
    acceleration    = 6.6906,
    turn_rate       = 0.7853981633974483,
    max_shield      = 624650,
    shield          = 624650,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 464,
    radar_range     = 350,
    cargobay        = 20000
WHERE ship_class_id = 79 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 141.048,
    acceleration    = 19.1268,
    turn_rate       = 0.7853981633974483,
    max_shield      = 4125000,
    shield          = 4125000,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 12144,
    radar_range     = 450,
    cargobay        = 852357
WHERE ship_class_id = 80 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 27.324,
    acceleration    = 9.5634,
    turn_rate       = 0.7853981633974483,
    max_shield      = 51030,
    shield          = 51030,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 2000
WHERE ship_class_id = 81 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 12.42,
    acceleration    = 4.347,
    turn_rate       = 0.7853981633974483,
    max_shield      = 990000,
    shield          = 990000,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1821,
    radar_range     = 450,
    cargobay        = 61760
WHERE ship_class_id = 82 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 21.384,
    acceleration    = 7.4844,
    turn_rate       = 0.7853981633974483,
    max_shield      = 470250,
    shield          = 470250,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 3795,
    radar_range     = 450,
    cargobay        = 2260
WHERE ship_class_id = 83 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 35.316,
    acceleration    = 26.487,
    turn_rate       = 0.7853981633974483,
    max_shield      = 43560,
    shield          = 43560,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 423,
    radar_range     = 450,
    cargobay        = 164
WHERE ship_class_id = 84 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 55.943999999999996,
    acceleration    = 47.5524,
    turn_rate       = 0.7853981633974483,
    max_shield      = 23870,
    shield          = 23870,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 204,
    radar_range     = 450,
    cargobay        = 65
WHERE ship_class_id = 85 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 71.928,
    acceleration    = 67.61232,
    turn_rate       = 0.7853981633974483,
    max_shield      = 8556,
    shield          = 8556,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 134,
    radar_range     = 500,
    cargobay        = 27
WHERE ship_class_id = 86 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 28.296,
    acceleration    = 9.9036,
    turn_rate       = 0.7853981633974483,
    max_shield      = 182160,
    shield          = 182160,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1191,
    radar_range     = 420,
    cargobay        = 1220
WHERE ship_class_id = 87 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 16.308,
    acceleration    = 5.7078,
    turn_rate       = 0.7853981633974483,
    max_shield      = 651000,
    shield          = 651000,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 406,
    radar_range     = 350,
    cargobay        = 24000
WHERE ship_class_id = 88 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 0.10800000000000001,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 2,
    shield          = 2,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 13,
    radar_range     = 450,
    cargobay        = 0
WHERE ship_class_id = 89 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 20.951999999999998,
    acceleration    = 7.3332,
    turn_rate       = 0.7853981633974483,
    max_shield      = 54675,
    shield          = 54675,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 3000
WHERE ship_class_id = 90 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 11.88,
    acceleration    = 4.158,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1039500,
    shield          = 1039500,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 2059,
    radar_range     = 450,
    cargobay        = 65000
WHERE ship_class_id = 91 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 20.304000000000002,
    acceleration    = 7.1064,
    turn_rate       = 0.7853981633974483,
    max_shield      = 569250,
    shield          = 569250,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4125,
    radar_range     = 450,
    cargobay        = 2700
WHERE ship_class_id = 92 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 38.123999999999995,
    acceleration    = 28.211759999999998,
    turn_rate       = 0.7853981633974483,
    max_shield      = 61050,
    shield          = 61050,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 469,
    radar_range     = 450,
    cargobay        = 112
WHERE ship_class_id = 93 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 50.976000000000006,
    acceleration    = 42.81336,
    turn_rate       = 0.7853981633974483,
    max_shield      = 26040,
    shield          = 26040,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 243,
    radar_range     = 450,
    cargobay        = 85
WHERE ship_class_id = 94 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 83.59200000000001,
    acceleration    = 100.3104,
    turn_rate       = 0.7853981633974483,
    max_shield      = 6045,
    shield          = 6045,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 130,
    radar_range     = 500,
    cargobay        = 25
WHERE ship_class_id = 95 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 26.136,
    acceleration    = 9.1476,
    turn_rate       = 0.7853981633974483,
    max_shield      = 247500,
    shield          = 247500,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1240,
    radar_range     = 420,
    cargobay        = 700
WHERE ship_class_id = 96 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 19.98,
    acceleration    = 6.992999999999999,
    turn_rate       = 0.7853981633974483,
    max_shield      = 581250,
    shield          = 581250,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 534,
    radar_range     = 350,
    cargobay        = 16000
WHERE ship_class_id = 97 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 29.268,
    acceleration    = 10.2438,
    turn_rate       = 0.7853981633974483,
    max_shield      = 676500,
    shield          = 676500,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4428,
    radar_range     = 450,
    cargobay        = 3500
WHERE ship_class_id = 98 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 31.32,
    acceleration    = 10.962,
    turn_rate       = 0.7853981633974483,
    max_shield      = 47250,
    shield          = 47250,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 1600
WHERE ship_class_id = 99 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 12.96,
    acceleration    = 4.5360000000000005,
    turn_rate       = 0.7853981633974483,
    max_shield      = 891000,
    shield          = 891000,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 2376,
    radar_range     = 450,
    cargobay        = 59800
WHERE ship_class_id = 100 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 24.3,
    acceleration    = 8.505,
    turn_rate       = 0.7853981633974483,
    max_shield      = 445500,
    shield          = 445500,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 5280,
    radar_range     = 450,
    cargobay        = 2260
WHERE ship_class_id = 101 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 41.903999999999996,
    acceleration    = 28.91376,
    turn_rate       = 0.7853981633974483,
    max_shield      = 34155,
    shield          = 34155,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 605,
    radar_range     = 450,
    cargobay        = 122
WHERE ship_class_id = 102 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 57.348,
    acceleration    = 45.304919999999996,
    turn_rate       = 0.7853981633974483,
    max_shield      = 20615,
    shield          = 20615,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 262,
    radar_range     = 450,
    cargobay        = 55
WHERE ship_class_id = 103 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 77.76,
    acceleration    = 69.2064,
    turn_rate       = 0.7853981633974483,
    max_shield      = 7440,
    shield          = 7440,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 165,
    radar_range     = 500,
    cargobay        = 38
WHERE ship_class_id = 104 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 33.48,
    acceleration    = 11.718,
    turn_rate       = 0.7853981633974483,
    max_shield      = 188100,
    shield          = 188100,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1528,
    radar_range     = 420,
    cargobay        = 620
WHERE ship_class_id = 105 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 20.951999999999998,
    acceleration    = 7.3332,
    turn_rate       = 0.7853981633974483,
    max_shield      = 483600,
    shield          = 483600,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 662,
    radar_range     = 350,
    cargobay        = 14800
WHERE ship_class_id = 106 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 0.10800000000000001,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 2,
    shield          = 2,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 13,
    radar_range     = 450,
    cargobay        = 0
WHERE ship_class_id = 107 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 33.48,
    acceleration    = 11.718,
    turn_rate       = 0.7853981633974483,
    max_shield      = 31995,
    shield          = 31995,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 1380
WHERE ship_class_id = 108 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 10.26,
    acceleration    = 3.591,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1188000,
    shield          = 1188000,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1663,
    radar_range     = 450,
    cargobay        = 72800
WHERE ship_class_id = 109 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 15.444,
    acceleration    = 5.4054,
    turn_rate       = 0.7853981633974483,
    max_shield      = 663300,
    shield          = 663300,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 2970,
    radar_range     = 450,
    cargobay        = 4060
WHERE ship_class_id = 110 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 33.48,
    acceleration    = 21.761999999999997,
    turn_rate       = 0.7853981633974483,
    max_shield      = 75900,
    shield          = 75900,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 359,
    radar_range     = 450,
    cargobay        = 194
WHERE ship_class_id = 111 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 48.168,
    acceleration    = 36.126000000000005,
    turn_rate       = 0.7853981633974483,
    max_shield      = 31465,
    shield          = 31465,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 194,
    radar_range     = 450,
    cargobay        = 97
WHERE ship_class_id = 112 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 60.912,
    acceleration    = 51.7752,
    turn_rate       = 0.7853981633974483,
    max_shield      = 12400,
    shield          = 12400,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 144,
    radar_range     = 500,
    cargobay        = 75
WHERE ship_class_id = 113 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 20.951999999999998,
    acceleration    = 7.3332,
    turn_rate       = 0.7853981633974483,
    max_shield      = 277200,
    shield          = 277200,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1289,
    radar_range     = 420,
    cargobay        = 1360
WHERE ship_class_id = 114 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 17.82,
    acceleration    = 6.237,
    turn_rate       = 0.7853981633974483,
    max_shield      = 759500,
    shield          = 759500,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 440,
    radar_range     = 350,
    cargobay        = 24800
WHERE ship_class_id = 115 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 0.10800000000000001,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 2,
    shield          = 2,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 13,
    radar_range     = 450,
    cargobay        = 0
WHERE ship_class_id = 116 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 23.004,
    acceleration    = 8.051400000000001,
    turn_rate       = 0.7853981633974483,
    max_shield      = 56700,
    shield          = 56700,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 2480
WHERE ship_class_id = 117 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 13.5,
    acceleration    = 4.725,
    turn_rate       = 0.7853981633974483,
    max_shield      = 990000,
    shield          = 990000,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 2139,
    radar_range     = 450,
    cargobay        = 58500
WHERE ship_class_id = 118 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 25.164,
    acceleration    = 8.8074,
    turn_rate       = 0.7853981633974483,
    max_shield      = 495000,
    shield          = 495000,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4455,
    radar_range     = 450,
    cargobay        = 4500
WHERE ship_class_id = 119 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 43.416000000000004,
    acceleration    = 30.825360000000003,
    turn_rate       = 0.7853981633974483,
    max_shield      = 42570,
    shield          = 42570,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 583,
    radar_range     = 450,
    cargobay        = 242
WHERE ship_class_id = 120 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 60.803999999999995,
    acceleration    = 49.25124,
    turn_rate       = 0.7853981633974483,
    max_shield      = 18600,
    shield          = 18600,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 301,
    radar_range     = 450,
    cargobay        = 120
WHERE ship_class_id = 121 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 86.184,
    acceleration    = 76.70376,
    turn_rate       = 0.7853981633974483,
    max_shield      = 10230,
    shield          = 10230,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 171,
    radar_range     = 500,
    cargobay        = 60
WHERE ship_class_id = 122 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 34.776,
    acceleration    = 12.1716,
    turn_rate       = 0.7853981633974483,
    max_shield      = 166320,
    shield          = 166320,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1587,
    radar_range     = 420,
    cargobay        = 960
WHERE ship_class_id = 123 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 23.22,
    acceleration    = 8.127,
    turn_rate       = 0.7853981633974483,
    max_shield      = 488250,
    shield          = 488250,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 626,
    radar_range     = 350,
    cargobay        = 14324
WHERE ship_class_id = 124 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":3},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 0.10800000000000001,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 2,
    shield          = 2,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 13,
    radar_range     = 450,
    cargobay        = 0
WHERE ship_class_id = 125 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 23.76,
    acceleration    = 8.316,
    turn_rate       = 0.7853981633974483,
    max_shield      = 36450,
    shield          = 36450,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 2500
WHERE ship_class_id = 126 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 15.120000000000001,
    acceleration    = 5.292000000000001,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1584000,
    shield          = 1584000,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4752,
    radar_range     = 450,
    cargobay        = 52000
WHERE ship_class_id = 127 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 20.088,
    acceleration    = 7.0308,
    turn_rate       = 0.7853981633974483,
    max_shield      = 660000,
    shield          = 660000,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4290,
    radar_range     = 450,
    cargobay        = 3460
WHERE ship_class_id = 128 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 37.8,
    acceleration    = 26.46,
    turn_rate       = 0.7853981633974483,
    max_shield      = 66000,
    shield          = 66000,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 454,
    radar_range     = 450,
    cargobay        = 230
WHERE ship_class_id = 129 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 57.348,
    acceleration    = 45.8784,
    turn_rate       = 0.7853981633974483,
    max_shield      = 28210,
    shield          = 28210,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 233,
    radar_range     = 450,
    cargobay        = 125
WHERE ship_class_id = 130 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 76.464,
    acceleration    = 68.8176,
    turn_rate       = 0.7853981633974483,
    max_shield      = 12090,
    shield          = 12090,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 156,
    radar_range     = 500,
    cargobay        = 58
WHERE ship_class_id = 131 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 30.240000000000002,
    acceleration    = 10.584000000000001,
    turn_rate       = 0.7853981633974483,
    max_shield      = 257400,
    shield          = 257400,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1289,
    radar_range     = 420,
    cargobay        = 1160
WHERE ship_class_id = 132 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 17.388,
    acceleration    = 6.0858,
    turn_rate       = 0.7853981633974483,
    max_shield      = 976500,
    shield          = 976500,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 850,
    radar_range     = 350,
    cargobay        = 0
WHERE ship_class_id = 133 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":115,"type":"up_turret_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 43.2,
    acceleration    = 37.26,
    turn_rate       = 0.7853981633974483,
    max_shield      = 99000,
    shield          = 99000,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 720,
    radar_range     = 450,
    cargobay        = 430
WHERE ship_class_id = 134 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 22.572,
    acceleration    = 7.900200000000001,
    turn_rate       = 0.7853981633974483,
    max_shield      = 72900,
    shield          = 72900,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 0
WHERE ship_class_id = 135 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":58,"type":"up_engine","level":1},{"equipmentID":38,"type":"up_shield","level":1},{"equipmentID":67,"type":"up_weapon_control","level":1},{"equipmentID":113,"type":"up_turret_control","level":3},{"equipmentID":1,"type":"up_launcher","level":5},{"equipmentID":10,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 15.120000000000001,
    acceleration    = 6.426,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1394250,
    shield          = 1394250,
    shield_recharge = 9598,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 4752,
    radar_range     = 450,
    cargobay        = 150000
WHERE ship_class_id = 136 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":59,"type":"up_engine","level":1},{"equipmentID":39,"type":"up_shield","level":1},{"equipmentID":68,"type":"up_weapon_control","level":1},{"equipmentID":114,"type":"up_turret_control","level":3},{"equipmentID":2,"type":"up_launcher","level":5},{"equipmentID":11,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 21.06,
    acceleration    = 10.017,
    turn_rate       = 0.7853981633974483,
    max_shield      = 1618650,
    shield          = 1618650,
    shield_recharge = 5627,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 5593,
    radar_range     = 450,
    cargobay        = 5000
WHERE ship_class_id = 137 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":60,"type":"up_engine","level":1},{"equipmentID":40,"type":"up_shield","level":1},{"equipmentID":69,"type":"up_weapon_control","level":1},{"equipmentID":3,"type":"up_launcher","level":5},{"equipmentID":12,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 38.34,
    acceleration    = 17.199,
    turn_rate       = 0.7853981633974483,
    max_shield      = 59400,
    shield          = 59400,
    shield_recharge = 699,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 677,
    radar_range     = 450,
    cargobay        = 530
WHERE ship_class_id = 138 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":61,"type":"up_engine","level":1},{"equipmentID":41,"type":"up_shield","level":1},{"equipmentID":70,"type":"up_weapon_control","level":1},{"equipmentID":4,"type":"up_launcher","level":4},{"equipmentID":13,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 62.208,
    acceleration    = 21.7728,
    turn_rate       = 0.7853981633974483,
    max_shield      = 34720,
    shield          = 34720,
    shield_recharge = 231,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 311,
    radar_range     = 450,
    cargobay        = 125
WHERE ship_class_id = 139 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":62,"type":"up_engine","level":1},{"equipmentID":42,"type":"up_shield","level":1},{"equipmentID":71,"type":"up_weapon_control","level":1},{"equipmentID":5,"type":"up_launcher","level":2},{"equipmentID":14,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 94.60799999999999,
    acceleration    = 33.1128,
    turn_rate       = 0.7853981633974483,
    max_shield      = 14880,
    shield          = 14880,
    shield_recharge = 88,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 162,
    radar_range     = 500,
    cargobay        = 58
WHERE ship_class_id = 140 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":63,"type":"up_engine","level":1},{"equipmentID":43,"type":"up_shield","level":1},{"equipmentID":72,"type":"up_weapon_control","level":1},{"equipmentID":116,"type":"up_turret_control","level":2},{"equipmentID":6,"type":"up_launcher","level":5},{"equipmentID":15,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 36.72,
    acceleration    = 12.852,
    turn_rate       = 0.7853981633974483,
    max_shield      = 323400,
    shield          = 323400,
    shield_recharge = 2145,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 1302,
    radar_range     = 420,
    cargobay        = 1150
WHERE ship_class_id = 141 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":64,"type":"up_engine","level":1},{"equipmentID":44,"type":"up_shield","level":1},{"equipmentID":73,"type":"up_weapon_control","level":1},{"equipmentID":117,"type":"up_turret_control","level":1},{"equipmentID":7,"type":"up_launcher","level":5},{"equipmentID":16,"type":"up_pro","level":4}]'::jsonb,
    max_speed       = 23.76,
    acceleration    = 6.0858,
    turn_rate       = 0.7853981633974483,
    max_shield      = 976500,
    shield          = 976500,
    shield_recharge = 6331,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 850,
    radar_range     = 350,
    cargobay        = 32000
WHERE ship_class_id = 142 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":65,"type":"up_engine","level":1},{"equipmentID":45,"type":"up_shield","level":1},{"equipmentID":74,"type":"up_weapon_control","level":1},{"equipmentID":138,"type":"up_turret_control","level":2},{"equipmentID":8,"type":"up_launcher","level":5},{"equipmentID":17,"type":"up_pro","level":5}]'::jsonb,
    max_speed       = 0.10800000000000001,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 2,
    shield          = 2,
    shield_recharge = 5715,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -300,
    laser_damage    = 13,
    radar_range     = 450,
    cargobay        = 0
WHERE ship_class_id = 143 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

UPDATE ships SET
    equipment       = '[{"equipmentID":66,"type":"up_engine","level":1},{"equipmentID":46,"type":"up_shield","level":1},{"equipmentID":9,"type":"up_launcher","level":5},{"equipmentID":18,"type":"up_pro","level":2}]'::jsonb,
    max_speed       = 22.572,
    acceleration    = 3.969,
    turn_rate       = 0.7853981633974483,
    max_shield      = 72900,
    shield          = 72900,
    shield_recharge = 539,
    max_energy      = 100,
    energy          = 100,
    energy_recharge = 2,
    energy_delta    = -200,
    laser_damage    = 10,
    radar_range     = 380,
    cargobay        = 0
WHERE ship_class_id = 144 AND equipment = '[]'::jsonb AND is_spacesuit = false
  AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Undo: strip the backfilled equipment back to '[]'. The stat columns are
-- left as-is (a no-op reverse would need every ship's pre-backfill values,
-- which are not recorded); a re-run of Up recomputes them from the class base.
UPDATE ships SET equipment = '[]'::jsonb
WHERE is_spacesuit = false AND player_id NOT IN (SELECT id FROM players WHERE login = '__npc__');
-- +goose StatementEnd
